#!/bin/bash

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"

# Todo
## IP=$(/sbin/ip route | awk '/default/ { print $3 }')
# echo $IP
# cat /etc/*-release
# sudo lsof -i -P -n | grep LISTEN
# Delete delete mozilla bookmarks backups 




# Conditional for ram swap in sudo mode 
#free_mem(){
#  sudo su; sync; echo 1 > /proc/sys/vm/drop_caches
#  exit
#}

#check_system(){
#  echo "free"
#  free -h
#  echo ""
#  echo "uptime"
#  uptime
#  echo ""
#  echo "tcp check"
#  cat /proc/net/tcp | wc -l
#  echo ""
#  echo "system name"
#  uname -r
#}


# function backup(){
  # backup safevaults
  # mozilla
  # .config?
# }

# function setup(){
  # ln -s bash zsh tmux 
  # download vim bundles zsh setup git
  # setup ssh
# }

