#!/bin/bash

ex () {
  file=$1
  [ -z "$file" ] && echo 'ex <compressed>' && return 1
  [ ! -f "$file" ] && echo 'Invalid file: `'$file'`' && return 1
  case $file in
    *.tar)      tar xf $file;
    *.tar.bz2)  tar xjf $file;;
    *.tar.gz)   tar xzf $file;;
    *.rar)      unrar x $file;;
    *.zip)      unzip $file;;
    *)          echo 'Unknown suffix on file: `'$file'`'; return 1;;
  esac
}
