#!/bin/bash


Color_Off='\033[0m'
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'

# install docker
# check for gh if is installed, hence snap
# create dirs, $HOME/repos/github.com/$gh_user/
for i in $(gh repo list --limit=58 | cut -f1)
do
  if [ -d "${i:13}" ] 
  then
    echo -e "${Yellow}[::]${Color_Off} Repo ${Red}${i:13}${Color_Off} already exist..."
  else
    echo -e "${Green}Cloning $i${Color_Off}"
    git clone git@github.com:$i.git # > gh repos patg
  fi
done

